# Generated by Cursor AI (Claude Sonnet 4) - 2025-01-06
# Purpose: Centralized aggregate function system for MapManagerCore image analysis
# Provides flexible, type-safe aggregate functions for ROI intensity calculations

from typing import Callable, Dict
import numpy as np

# Type definitions for aggregate functions
AggregateFunc = Callable[[np.ndarray], float | int]
AggregatesDict = Dict[str, AggregateFunc]

def _safe_std(arr: np.ndarray) -> float:
    """Safe standard deviation that handles edge cases."""
    n = arr.size
    if n <= 1:
        return 0.0
    return float(np.std(arr, ddof=1))

def _safe_cv(arr: np.ndarray) -> float:
    """Coefficient of variation (std/mean) with safe handling of zero mean."""
    mean = float(np.mean(arr))
    if mean == 0.0:
        return float('nan')
    return _safe_std(arr) / mean

# Default aggregate functions available to all schemas
DEFAULT_AGGREGATES: AggregatesDict = {
    "count": lambda arr: int(arr.size),
    "sum":   lambda arr: float(np.sum(arr)),
    "mean":  lambda arr: float(np.mean(arr)),
    "median": lambda arr: float(np.median(arr)),
    "min":   lambda arr: float(np.min(arr)),
    "max":   lambda arr: float(np.max(arr)),
    "std":   _safe_std,
    "cv":    _safe_cv,
}

# Schema-specific aggregate presets
def get_spine_aggregates() -> AggregatesDict:
    """Get aggregate functions specifically for Spine schema."""
    spine_aggregates = DEFAULT_AGGREGATES.copy()
    
    # Add spine-specific custom aggregates
    def _custom_percentile_95(arr: np.ndarray) -> float:
        """95th percentile of the data."""
        if arr.size == 0:
            return float('nan')
        return float(np.percentile(arr, 95))
    
    spine_aggregates["p95"] = _custom_percentile_95
    return spine_aggregates

def get_segment_aggregates() -> AggregatesDict:
    """Get aggregate functions specifically for Segment schema."""
    # For now, use default aggregates
    # Can be extended with segment-specific functions in the future
    return DEFAULT_AGGREGATES.copy()

# Legacy support for backward compatibility
def legacy_aggregate_to_dict(agg_list: list[str]) -> AggregatesDict:
    """Convert legacy aggregate list to new dict format."""
    result = {}
    for agg in agg_list:
        if agg in DEFAULT_AGGREGATES:
            result[agg] = DEFAULT_AGGREGATES[agg]
        else:
            # Fallback to numpy function if not in defaults
            try:
                result[agg] = lambda arr, func=agg: float(getattr(np, func)(arr))
            except AttributeError:
                import logging
                logging.warning(f"Unknown aggregate function: {agg}")
                result[agg] = lambda arr: float('nan')
    return result
