name: Test (cudmore)

on:
  pull_request:
    branches: [main]
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        # pip install -e .
        pip install '.[tests]'

    - name: Run flake8
      run: |
        flake8 ./mapmanagercore --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test and generate coverage report
      run: |
        pytest --cov=./tests --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
